Stupid compiler does not know diff arg/member!
There are compilers that get confused by this:

struct boyer_moor {
    unsigned int   needle_len;
    char*          needle;

    static void    prepare_badcharacter_heuristic(char const* needle,
                                                  int needle_len,
                                                  int* result);
};

because the names "needle" and "needle_len" appear both as struct
members and function parameter names, "because they're in the same
scope". Sheesh.

icpc: /usr/local/src/jive5ab-3.0.0-rc1/src/boyer_moore.cc(130): error #3868:
declaration hides member "boyer_moore::needle" (declared at line 54 of
"/usr/local/src/jive5ab-3.0.0-rc1/src/boyer_moore.h") in same scope
 void boyer_moore::prepare_badcharacter_heuristic(char const* needle,
int needle_len, int* result) {

... Intel *sigh*