Fix sciprint<unsigned int,...>
For unsigned quantities there is no std::abs() function so need template
specialization

In file included from
/home/oper/eskil/j5a-3rc1/jive5ab-3.0.0-rc1/src/test.cc:53:0:
/home/oper/eskil/j5a-3rc1/jive5ab-3.0.0-rc1/src/sciprint.h: In
instantiation of ‘T absfn(const T&) [with T = unsigned int]’:
/home/oper/eskil/j5a-3rc1/jive5ab-3.0.0-rc1/src/sciprint.h:128:41:
required from ‘std::ostream& operator<<(std::ostream&, const sciprint<T,
_thous>&) [with T = unsigned int; unsigned int _thous = 1024;
std::ostream = std::basic_ostream<char>]’
/home/oper/eskil/j5a-3rc1/jive5ab-3.0.0-rc1/src/test.cc:437:79:
required from here
/home/oper/eskil/j5a-3rc1/jive5ab-3.0.0-rc1/src/sciprint.h:103:17:
error: call of overloaded ‘abs(const unsigned int&)’ is ambiguous
     return ::abs(t);
            ~~~~~^~~