fix non-throw specification/missing const_cast
"clang" trying to compile v3.0.0-rc1 yields two problems:
    const void* => void* w/o const_cast

    destructor marked non-throwing could throw pthreadexception

In file included from
/usr/local/src/jive5ab-3.0.0-rc1/src/byteorder.cc:20:
In file included from
/usr/local/src/jive5ab-3.0.0-rc1/src/byteorder.h:25:
/usr/local/src/jive5ab-3.0.0-rc1/src/countedpointer.h:196:27: error:
cast from 'const type-parameter-1-0 *' to 'void *' drops const qualifier
[-Werror,-Wcast-qual]
               myPointer = new ((void*)cpbptr) typename
countedpointer<T>::cPtrBlock((unsigned int)0);
                                       ^
/usr/local/src/jive5ab-3.0.0-rc1/src/countedpointer.h:303:2: error:
'~cPtrBlock' has a non-throwing exception specification but can still
throw [-Werror,-Wexceptions]
       PTHREAD_CALL( ::pthread_mutex_destroy(&mtx) );
       ^
/usr/local/src/jive5ab-3.0.0-rc1/src/pthreadcall.h:83:5: note: expanded
from macro 'PTHREAD_CALL'
   PTHREAD2_CALL( a, ; )
   ^
/usr/local/src/jive5ab-3.0.0-rc1/src/pthreadcall.h:78:13: note: expanded
from macro 'PTHREAD2_CALL'
           throw pthreadexception(lclStreAmvar_q8.str());\
           ^            ~~~~~~~