Fix uninitialized use warning(=error) on Debian6
JonQ: on my Mark6 w/ Debian6 compiler now warns:

    jive5ab/src/mk6info.cc: In function 'sockaddr_in empty_IPv4_address()':
    jive5ab-git/jive5ab/src/mk6info.cc:314: error:
        'rv.sockaddr_in::sin_zero[7u]' is used uninitialized in this function

    (and some more lines).

Fixed by wrapping the return value in the (specially designed for that)
    Zero<struct sockaddr_in> rv;